[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/api/:splat"